# Generated by Django 4.2.5 on 2023-09-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_id_detail_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='user_id',
            new_name='user',
        ),
    ]
